package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.4
 * Generated source version: 3.4.4
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IPacientesService")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, org.datacontract.schemas._2004._07.ua_directorio_business_services_directorio.ObjectFactory.class, org.datacontract.schemas._2004._07.ua_core.ObjectFactory.class, ObjectFactory.class, org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules_pacientes.ObjectFactory.class, org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules_pacientesservice.ObjectFactory.class, org.datacontract.schemas._2004._07.wcfinterfaz.ObjectFactory.class, org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules.ObjectFactory.class})
public interface IPacientesService {

    @WebMethod(operationName = "CodigosTelefono", action = "http://tempuri.org/IPacientesService/CodigosTelefono")
    @Action(input = "http://tempuri.org/IPacientesService/CodigosTelefono", output = "http://tempuri.org/IPacientesService/CodigosTelefonoResponse")
    @RequestWrapper(localName = "CodigosTelefono", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CodigosTelefono")
    @ResponseWrapper(localName = "CodigosTelefonoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CodigosTelefonoResponse")
    @WebResult(name = "CodigosTelefonoResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_core.ArrayOfListItemModel codigosTelefono()
;

    @WebMethod(operationName = "ValidarCodigosTelefono", action = "http://tempuri.org/IPacientesService/ValidarCodigosTelefono")
    @Action(input = "http://tempuri.org/IPacientesService/ValidarCodigosTelefono", output = "http://tempuri.org/IPacientesService/ValidarCodigosTelefonoResponse")
    @RequestWrapper(localName = "ValidarCodigosTelefono", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidarCodigosTelefono")
    @ResponseWrapper(localName = "ValidarCodigosTelefonoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidarCodigosTelefonoResponse")
    @WebResult(name = "ValidarCodigosTelefonoResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Boolean validarCodigosTelefono(

        @WebParam(name = "codigo", targetNamespace = "http://tempuri.org/")
        java.lang.Integer codigo
    );

    @WebMethod(operationName = "EnviarMailLaboratorio", action = "http://tempuri.org/IPacientesService/EnviarMailLaboratorio")
    @Action(input = "http://tempuri.org/IPacientesService/EnviarMailLaboratorio", output = "http://tempuri.org/IPacientesService/EnviarMailLaboratorioResponse")
    @RequestWrapper(localName = "EnviarMailLaboratorio", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EnviarMailLaboratorio")
    @ResponseWrapper(localName = "EnviarMailLaboratorioResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EnviarMailLaboratorioResponse")
    @WebResult(name = "EnviarMailLaboratorioResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Boolean enviarMailLaboratorio(

        @WebParam(name = "_historiaClinica", targetNamespace = "http://tempuri.org/")
        java.lang.String historiaClinica,
        @WebParam(name = "_timeStampEstudio", targetNamespace = "http://tempuri.org/")
        java.lang.String timeStampEstudio,
        @WebParam(name = "_observaciones", targetNamespace = "http://tempuri.org/")
        java.lang.String observaciones,
        @WebParam(name = "_nombreAdjunto", targetNamespace = "http://tempuri.org/")
        java.lang.String nombreAdjunto,
        @WebParam(name = "_sede", targetNamespace = "http://tempuri.org/")
        java.lang.Integer sede,
        @WebParam(name = "_adjunto", targetNamespace = "http://tempuri.org/")
        java.lang.String adjunto
    );

    @WebMethod(operationName = "ModificarPacienteService", action = "http://tempuri.org/IPacientesService/ModificarPacienteService")
    @Action(input = "http://tempuri.org/IPacientesService/ModificarPacienteService", output = "http://tempuri.org/IPacientesService/ModificarPacienteServiceResponse")
    @RequestWrapper(localName = "ModificarPacienteService", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ModificarPacienteService")
    @ResponseWrapper(localName = "ModificarPacienteServiceResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ModificarPacienteServiceResponse")
    public void modificarPacienteService(

        @WebParam(name = "model", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules_pacientesservice.DatosPersonalesModel model
    );

    @WebMethod(operationName = "DeconstruccionTelefono", action = "http://tempuri.org/IPacientesService/DeconstruccionTelefono")
    @Action(input = "http://tempuri.org/IPacientesService/DeconstruccionTelefono", output = "http://tempuri.org/IPacientesService/DeconstruccionTelefonoResponse")
    @RequestWrapper(localName = "DeconstruccionTelefono", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeconstruccionTelefono")
    @ResponseWrapper(localName = "DeconstruccionTelefonoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeconstruccionTelefonoResponse")
    @WebResult(name = "DeconstruccionTelefonoResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_directorio_business_services_directorio.TelefonoModel deconstruccionTelefono(

        @WebParam(name = "telefono", targetNamespace = "http://tempuri.org/")
        java.lang.String telefono,
        @WebParam(name = "con15", targetNamespace = "http://tempuri.org/")
        java.lang.Boolean con15
    );

    @WebMethod(operationName = "DatosPersonalesPaciente", action = "http://tempuri.org/IPacientesService/DatosPersonalesPaciente")
    @Action(input = "http://tempuri.org/IPacientesService/DatosPersonalesPaciente", output = "http://tempuri.org/IPacientesService/DatosPersonalesPacienteResponse")
    @RequestWrapper(localName = "DatosPersonalesPaciente", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DatosPersonalesPaciente")
    @ResponseWrapper(localName = "DatosPersonalesPacienteResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DatosPersonalesPacienteResponse")
    @WebResult(name = "DatosPersonalesPacienteResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules_pacientesservice.DatosPersonalesModel datosPersonalesPaciente(

        @WebParam(name = "pacienteId", targetNamespace = "http://tempuri.org/")
        java.lang.String pacienteId,
        @WebParam(name = "tipoDocumentoId", targetNamespace = "http://tempuri.org/")
        java.lang.String tipoDocumentoId
    );

    @WebMethod(operationName = "ObtenerLabCodePaciente", action = "http://tempuri.org/IPacientesService/ObtenerLabCodePaciente")
    @Action(input = "http://tempuri.org/IPacientesService/ObtenerLabCodePaciente", output = "http://tempuri.org/IPacientesService/ObtenerLabCodePacienteResponse")
    @RequestWrapper(localName = "ObtenerLabCodePaciente", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerLabCodePaciente")
    @ResponseWrapper(localName = "ObtenerLabCodePacienteResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerLabCodePacienteResponse")
    @WebResult(name = "ObtenerLabCodePacienteResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Long obtenerLabCodePaciente(

        @WebParam(name = "pacienteId", targetNamespace = "http://tempuri.org/")
        java.lang.String pacienteId
    );

    @WebMethod(operationName = "EnviarMailDesbloqueoPreguntaSecreta", action = "http://tempuri.org/IPacientesService/EnviarMailDesbloqueoPreguntaSecreta")
    @Action(input = "http://tempuri.org/IPacientesService/EnviarMailDesbloqueoPreguntaSecreta", output = "http://tempuri.org/IPacientesService/EnviarMailDesbloqueoPreguntaSecretaResponse")
    @RequestWrapper(localName = "EnviarMailDesbloqueoPreguntaSecreta", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EnviarMailDesbloqueoPreguntaSecreta")
    @ResponseWrapper(localName = "EnviarMailDesbloqueoPreguntaSecretaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EnviarMailDesbloqueoPreguntaSecretaResponse")
    @WebResult(name = "EnviarMailDesbloqueoPreguntaSecretaResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules.ResultadoOperacion enviarMailDesbloqueoPreguntaSecreta(

        @WebParam(name = "tipoDeDocumento", targetNamespace = "http://tempuri.org/")
        java.lang.String tipoDeDocumento,
        @WebParam(name = "numeroDeDocumento", targetNamespace = "http://tempuri.org/")
        java.lang.String numeroDeDocumento
    );

    @WebMethod(operationName = "ProcesarCoberturaPaciente", action = "http://tempuri.org/IPacientesService/ProcesarCoberturaPaciente")
    @Action(input = "http://tempuri.org/IPacientesService/ProcesarCoberturaPaciente", output = "http://tempuri.org/IPacientesService/ProcesarCoberturaPacienteResponse")
    @RequestWrapper(localName = "ProcesarCoberturaPaciente", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ProcesarCoberturaPaciente")
    @ResponseWrapper(localName = "ProcesarCoberturaPacienteResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ProcesarCoberturaPacienteResponse")
    @WebResult(name = "ProcesarCoberturaPacienteResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules.ResultadoOperacion procesarCoberturaPaciente(

        @WebParam(name = "cobertura", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules_pacientesservice.CoberturaModel cobertura,
        @WebParam(name = "tipoNovedad", targetNamespace = "http://tempuri.org/")
        java.lang.String tipoNovedad,
        @WebParam(name = "idPaciente", targetNamespace = "http://tempuri.org/")
        java.lang.Long idPaciente
    );

    @WebMethod(operationName = "LoadImagenPaciente", action = "http://tempuri.org/IPacientesService/LoadImagenPaciente")
    @Action(input = "http://tempuri.org/IPacientesService/LoadImagenPaciente", output = "http://tempuri.org/IPacientesService/LoadImagenPacienteResponse")
    @RequestWrapper(localName = "LoadImagenPaciente", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LoadImagenPaciente")
    @ResponseWrapper(localName = "LoadImagenPacienteResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LoadImagenPacienteResponse")
    @WebResult(name = "LoadImagenPacienteResult", targetNamespace = "http://tempuri.org/")
    public byte[] loadImagenPaciente(

        @WebParam(name = "pacienteId", targetNamespace = "http://tempuri.org/")
        java.lang.String pacienteId,
        @WebParam(name = "extension", targetNamespace = "http://tempuri.org/")
        java.lang.String extension
    );

    @WebMethod(operationName = "EnviarMailsActivacion", action = "http://tempuri.org/IPacientesService/EnviarMailsActivacion")
    @Action(input = "http://tempuri.org/IPacientesService/EnviarMailsActivacion", output = "http://tempuri.org/IPacientesService/EnviarMailsActivacionResponse")
    @RequestWrapper(localName = "EnviarMailsActivacion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EnviarMailsActivacion")
    @ResponseWrapper(localName = "EnviarMailsActivacionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EnviarMailsActivacionResponse")
    @WebResult(name = "EnviarMailsActivacionResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules.ArrayOfResultadoOperacion enviarMailsActivacion(

        @WebParam(name = "labCodePacientes", targetNamespace = "http://tempuri.org/")
        java.lang.String labCodePacientes
    );

    @WebMethod(operationName = "EnviarMailGeneracionPin", action = "http://tempuri.org/IPacientesService/EnviarMailGeneracionPin")
    @Action(input = "http://tempuri.org/IPacientesService/EnviarMailGeneracionPin", output = "http://tempuri.org/IPacientesService/EnviarMailGeneracionPinResponse")
    @RequestWrapper(localName = "EnviarMailGeneracionPin", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EnviarMailGeneracionPin")
    @ResponseWrapper(localName = "EnviarMailGeneracionPinResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EnviarMailGeneracionPinResponse")
    @WebResult(name = "EnviarMailGeneracionPinResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules.ResultadoOperacion enviarMailGeneracionPin(

        @WebParam(name = "pacienteId", targetNamespace = "http://tempuri.org/")
        java.lang.String pacienteId
    );

    @WebMethod(operationName = "ObtenerVinculosGestionados", action = "http://tempuri.org/IPacientesService/ObtenerVinculosGestionados")
    @Action(input = "http://tempuri.org/IPacientesService/ObtenerVinculosGestionados", output = "http://tempuri.org/IPacientesService/ObtenerVinculosGestionadosResponse")
    @RequestWrapper(localName = "ObtenerVinculosGestionados", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerVinculosGestionados")
    @ResponseWrapper(localName = "ObtenerVinculosGestionadosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerVinculosGestionadosResponse")
    @WebResult(name = "ObtenerVinculosGestionadosResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules_pacientesservice.ArrayOfVinculoFamiliarModel obtenerVinculosGestionados(

        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        java.lang.String id
    );

    @WebMethod(operationName = "ObtenerLocalidades", action = "http://tempuri.org/IPacientesService/ObtenerLocalidades")
    @Action(input = "http://tempuri.org/IPacientesService/ObtenerLocalidades", output = "http://tempuri.org/IPacientesService/ObtenerLocalidadesResponse")
    @RequestWrapper(localName = "ObtenerLocalidades", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerLocalidades")
    @ResponseWrapper(localName = "ObtenerLocalidadesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerLocalidadesResponse")
    @WebResult(name = "ObtenerLocalidadesResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_core.ArrayOfListItemModel obtenerLocalidades(

        @WebParam(name = "partido", targetNamespace = "http://tempuri.org/")
        java.lang.String partido
    );

    @WebMethod(operationName = "ObtenerPreguntasSecretas", action = "http://tempuri.org/IPacientesService/ObtenerPreguntasSecretas")
    @Action(input = "http://tempuri.org/IPacientesService/ObtenerPreguntasSecretas", output = "http://tempuri.org/IPacientesService/ObtenerPreguntasSecretasResponse")
    @RequestWrapper(localName = "ObtenerPreguntasSecretas", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerPreguntasSecretas")
    @ResponseWrapper(localName = "ObtenerPreguntasSecretasResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerPreguntasSecretasResponse")
    @WebResult(name = "ObtenerPreguntasSecretasResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_core.ArrayOfListItemModel obtenerPreguntasSecretas()
;

    @WebMethod(operationName = "ConfirmarLimpiezaSeguridad", action = "http://tempuri.org/IPacientesService/ConfirmarLimpiezaSeguridad")
    @Action(input = "http://tempuri.org/IPacientesService/ConfirmarLimpiezaSeguridad", output = "http://tempuri.org/IPacientesService/ConfirmarLimpiezaSeguridadResponse")
    @RequestWrapper(localName = "ConfirmarLimpiezaSeguridad", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConfirmarLimpiezaSeguridad")
    @ResponseWrapper(localName = "ConfirmarLimpiezaSeguridadResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConfirmarLimpiezaSeguridadResponse")
    @WebResult(name = "ConfirmarLimpiezaSeguridadResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules.ResultadoOperacion confirmarLimpiezaSeguridad(

        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        java.lang.String token,
        @WebParam(name = "tipoDeDocumento", targetNamespace = "http://tempuri.org/")
        java.lang.String tipoDeDocumento,
        @WebParam(name = "numeroDeDocumento", targetNamespace = "http://tempuri.org/")
        java.lang.String numeroDeDocumento,
        @WebParam(name = "preguntaSecretaId", targetNamespace = "http://tempuri.org/")
        java.lang.String preguntaSecretaId,
        @WebParam(name = "respuesta", targetNamespace = "http://tempuri.org/")
        java.lang.String respuesta,
        @WebParam(name = "clave", targetNamespace = "http://tempuri.org/")
        java.lang.String clave
    );

    @WebMethod(operationName = "GetBodyMailLinkGeneracionPin", action = "http://tempuri.org/IPacientesService/GetBodyMailLinkGeneracionPin")
    @Action(input = "http://tempuri.org/IPacientesService/GetBodyMailLinkGeneracionPin", output = "http://tempuri.org/IPacientesService/GetBodyMailLinkGeneracionPinResponse")
    @RequestWrapper(localName = "GetBodyMailLinkGeneracionPin", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBodyMailLinkGeneracionPin")
    @ResponseWrapper(localName = "GetBodyMailLinkGeneracionPinResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBodyMailLinkGeneracionPinResponse")
    @WebResult(name = "GetBodyMailLinkGeneracionPinResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getBodyMailLinkGeneracionPin(

        @WebParam(name = "pacienteReducidoWrapper", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules.PacienteReducidoWrapper pacienteReducidoWrapper
    );

    @WebMethod(operationName = "ObtenerProvincias", action = "http://tempuri.org/IPacientesService/ObtenerProvincias")
    @Action(input = "http://tempuri.org/IPacientesService/ObtenerProvincias", output = "http://tempuri.org/IPacientesService/ObtenerProvinciasResponse")
    @RequestWrapper(localName = "ObtenerProvincias", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerProvincias")
    @ResponseWrapper(localName = "ObtenerProvinciasResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerProvinciasResponse")
    @WebResult(name = "ObtenerProvinciasResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_core.ArrayOfListItemModel obtenerProvincias(

        @WebParam(name = "pais", targetNamespace = "http://tempuri.org/")
        java.lang.String pais
    );

    @WebMethod(operationName = "CambioDeClave", action = "http://tempuri.org/IPacientesService/CambioDeClave")
    @Action(input = "http://tempuri.org/IPacientesService/CambioDeClave", output = "http://tempuri.org/IPacientesService/CambioDeClaveResponse")
    @RequestWrapper(localName = "CambioDeClave", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CambioDeClave")
    @ResponseWrapper(localName = "CambioDeClaveResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CambioDeClaveResponse")
    @WebResult(name = "CambioDeClaveResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules.ResultadoOperacion cambioDeClave(

        @WebParam(name = "tipoDeDocumento", targetNamespace = "http://tempuri.org/")
        java.lang.String tipoDeDocumento,
        @WebParam(name = "numeroDeDocumento", targetNamespace = "http://tempuri.org/")
        java.lang.String numeroDeDocumento,
        @WebParam(name = "claveNueva", targetNamespace = "http://tempuri.org/")
        java.lang.String claveNueva,
        @WebParam(name = "confirmacionClaveNueva", targetNamespace = "http://tempuri.org/")
        java.lang.String confirmacionClaveNueva
    );

    @WebMethod(operationName = "DesactivarPaciente", action = "http://tempuri.org/IPacientesService/DesactivarPaciente")
    @Action(input = "http://tempuri.org/IPacientesService/DesactivarPaciente", output = "http://tempuri.org/IPacientesService/DesactivarPacienteResponse")
    @RequestWrapper(localName = "DesactivarPaciente", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DesactivarPaciente")
    @ResponseWrapper(localName = "DesactivarPacienteResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DesactivarPacienteResponse")
    @WebResult(name = "DesactivarPacienteResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules.ResultadoOperacion desactivarPaciente(

        @WebParam(name = "pacienteId", targetNamespace = "http://tempuri.org/")
        java.lang.String pacienteId
    );

    @WebMethod(operationName = "EnviarMailConfirmaCorreo", action = "http://tempuri.org/IPacientesService/EnviarMailConfirmaCorreo")
    @Action(input = "http://tempuri.org/IPacientesService/EnviarMailConfirmaCorreo", output = "http://tempuri.org/IPacientesService/EnviarMailConfirmaCorreoResponse")
    @RequestWrapper(localName = "EnviarMailConfirmaCorreo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EnviarMailConfirmaCorreo")
    @ResponseWrapper(localName = "EnviarMailConfirmaCorreoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EnviarMailConfirmaCorreoResponse")
    @WebResult(name = "EnviarMailConfirmaCorreoResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Boolean enviarMailConfirmaCorreo(

        @WebParam(name = "_id", targetNamespace = "http://tempuri.org/")
        java.lang.String id,
        @WebParam(name = "_link", targetNamespace = "http://tempuri.org/")
        java.lang.String link,
        @WebParam(name = "_email", targetNamespace = "http://tempuri.org/")
        java.lang.String email,
        @WebParam(name = "_vigencia", targetNamespace = "http://tempuri.org/")
        java.lang.String vigencia
    );

    @WebMethod(operationName = "EnviarMailNotificarCambioCorreo", action = "http://tempuri.org/IPacientesService/EnviarMailNotificarCambioCorreo")
    @Action(input = "http://tempuri.org/IPacientesService/EnviarMailNotificarCambioCorreo", output = "http://tempuri.org/IPacientesService/EnviarMailNotificarCambioCorreoResponse")
    @RequestWrapper(localName = "EnviarMailNotificarCambioCorreo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EnviarMailNotificarCambioCorreo")
    @ResponseWrapper(localName = "EnviarMailNotificarCambioCorreoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EnviarMailNotificarCambioCorreoResponse")
    @WebResult(name = "EnviarMailNotificarCambioCorreoResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Boolean enviarMailNotificarCambioCorreo(

        @WebParam(name = "_id", targetNamespace = "http://tempuri.org/")
        java.lang.String id,
        @WebParam(name = "_email", targetNamespace = "http://tempuri.org/")
        java.lang.String email,
        @WebParam(name = "_nuevoEmail", targetNamespace = "http://tempuri.org/")
        java.lang.String nuevoEmail
    );

    @WebMethod(operationName = "GuardarHuellaDigital", action = "http://tempuri.org/IPacientesService/GuardarHuellaDigital")
    @Action(input = "http://tempuri.org/IPacientesService/GuardarHuellaDigital", output = "http://tempuri.org/IPacientesService/GuardarHuellaDigitalResponse")
    @RequestWrapper(localName = "GuardarHuellaDigital", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GuardarHuellaDigital")
    @ResponseWrapper(localName = "GuardarHuellaDigitalResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GuardarHuellaDigitalResponse")
    @WebResult(name = "GuardarHuellaDigitalResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules.ResultadoOperacion guardarHuellaDigital(

        @WebParam(name = "huella", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules_pacientesservice.HuellaModel huella
    );

    @WebMethod(operationName = "ObtenerPacientesSinPlanSaludSinPinConEmailValidoAtendidos", action = "http://tempuri.org/IPacientesService/ObtenerPacientesSinPlanSaludSinPinConEmailValidoAtendidos")
    @Action(input = "http://tempuri.org/IPacientesService/ObtenerPacientesSinPlanSaludSinPinConEmailValidoAtendidos", output = "http://tempuri.org/IPacientesService/ObtenerPacientesSinPlanSaludSinPinConEmailValidoAtendidosResponse")
    @RequestWrapper(localName = "ObtenerPacientesSinPlanSaludSinPinConEmailValidoAtendidos", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerPacientesSinPlanSaludSinPinConEmailValidoAtendidos")
    @ResponseWrapper(localName = "ObtenerPacientesSinPlanSaludSinPinConEmailValidoAtendidosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerPacientesSinPlanSaludSinPinConEmailValidoAtendidosResponse")
    @WebResult(name = "ObtenerPacientesSinPlanSaludSinPinConEmailValidoAtendidosResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules.PacientesReducidosWrapper obtenerPacientesSinPlanSaludSinPinConEmailValidoAtendidos(

        @WebParam(name = "fechaDesde", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fechaDesde,
        @WebParam(name = "fechaHasta", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fechaHasta
    );

    @WebMethod(operationName = "EsValidoLinkGeneracionPin", action = "http://tempuri.org/IPacientesService/EsValidoLinkGeneracionPin")
    @Action(input = "http://tempuri.org/IPacientesService/EsValidoLinkGeneracionPin", output = "http://tempuri.org/IPacientesService/EsValidoLinkGeneracionPinResponse")
    @RequestWrapper(localName = "EsValidoLinkGeneracionPin", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EsValidoLinkGeneracionPin")
    @ResponseWrapper(localName = "EsValidoLinkGeneracionPinResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EsValidoLinkGeneracionPinResponse")
    @WebResult(name = "EsValidoLinkGeneracionPinResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Boolean esValidoLinkGeneracionPin(

        @WebParam(name = "linkId", targetNamespace = "http://tempuri.org/")
        java.lang.String linkId,
        @WebParam(name = "pacienteId", targetNamespace = "http://tempuri.org/")
        java.lang.String pacienteId
    );

    @WebMethod(operationName = "InformarPaciente", action = "http://tempuri.org/IPacientesService/InformarPaciente")
    @Action(input = "http://tempuri.org/IPacientesService/InformarPaciente", output = "http://tempuri.org/IPacientesService/InformarPacienteResponse")
    @RequestWrapper(localName = "InformarPaciente", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InformarPaciente")
    @ResponseWrapper(localName = "InformarPacienteResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InformarPacienteResponse")
    @WebResult(name = "InformarPacienteResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules.ResultadoOperacion informarPaciente(

        @WebParam(name = "paciente", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules_pacientesservice.PacienteModel paciente
    );

    @WebMethod(operationName = "ValidarPacientePlanSalud", action = "http://tempuri.org/IPacientesService/ValidarPacientePlanSalud")
    @Action(input = "http://tempuri.org/IPacientesService/ValidarPacientePlanSalud", output = "http://tempuri.org/IPacientesService/ValidarPacientePlanSaludResponse")
    @RequestWrapper(localName = "ValidarPacientePlanSalud", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidarPacientePlanSalud")
    @ResponseWrapper(localName = "ValidarPacientePlanSaludResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidarPacientePlanSaludResponse")
    @WebResult(name = "ValidarPacientePlanSaludResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Boolean validarPacientePlanSalud(

        @WebParam(name = "tipoDeDocumento", targetNamespace = "http://tempuri.org/")
        java.lang.String tipoDeDocumento,
        @WebParam(name = "numeroDeDocumento", targetNamespace = "http://tempuri.org/")
        java.lang.String numeroDeDocumento
    );

    @WebMethod(operationName = "ObtenerPacientesConPinMasivoNoGenerado", action = "http://tempuri.org/IPacientesService/ObtenerPacientesConPinMasivoNoGenerado")
    @Action(input = "http://tempuri.org/IPacientesService/ObtenerPacientesConPinMasivoNoGenerado", output = "http://tempuri.org/IPacientesService/ObtenerPacientesConPinMasivoNoGeneradoResponse")
    @RequestWrapper(localName = "ObtenerPacientesConPinMasivoNoGenerado", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerPacientesConPinMasivoNoGenerado")
    @ResponseWrapper(localName = "ObtenerPacientesConPinMasivoNoGeneradoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerPacientesConPinMasivoNoGeneradoResponse")
    @WebResult(name = "ObtenerPacientesConPinMasivoNoGeneradoResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules.PacientesReducidosWrapper obtenerPacientesConPinMasivoNoGenerado()
;

    @WebMethod(operationName = "ObtenerVinculosFamiliares", action = "http://tempuri.org/IPacientesService/ObtenerVinculosFamiliares")
    @Action(input = "http://tempuri.org/IPacientesService/ObtenerVinculosFamiliares", output = "http://tempuri.org/IPacientesService/ObtenerVinculosFamiliaresResponse")
    @RequestWrapper(localName = "ObtenerVinculosFamiliares", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerVinculosFamiliares")
    @ResponseWrapper(localName = "ObtenerVinculosFamiliaresResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerVinculosFamiliaresResponse")
    @WebResult(name = "ObtenerVinculosFamiliaresResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules_pacientesservice.ArrayOfVinculoFamiliarModel obtenerVinculosFamiliares(

        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        java.lang.String id
    );

    @WebMethod(operationName = "ObtenerHuellaDigital", action = "http://tempuri.org/IPacientesService/ObtenerHuellaDigital")
    @Action(input = "http://tempuri.org/IPacientesService/ObtenerHuellaDigital", output = "http://tempuri.org/IPacientesService/ObtenerHuellaDigitalResponse")
    @RequestWrapper(localName = "ObtenerHuellaDigital", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerHuellaDigital")
    @ResponseWrapper(localName = "ObtenerHuellaDigitalResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerHuellaDigitalResponse")
    @WebResult(name = "ObtenerHuellaDigitalResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules_pacientesservice.HuellaModel obtenerHuellaDigital(

        @WebParam(name = "pacienteId", targetNamespace = "http://tempuri.org/")
        java.lang.String pacienteId
    );

    @WebMethod(operationName = "CantidadPacientesSinPlanSaludSinPin", action = "http://tempuri.org/IPacientesService/CantidadPacientesSinPlanSaludSinPin")
    @Action(input = "http://tempuri.org/IPacientesService/CantidadPacientesSinPlanSaludSinPin", output = "http://tempuri.org/IPacientesService/CantidadPacientesSinPlanSaludSinPinResponse")
    @RequestWrapper(localName = "CantidadPacientesSinPlanSaludSinPin", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CantidadPacientesSinPlanSaludSinPin")
    @ResponseWrapper(localName = "CantidadPacientesSinPlanSaludSinPinResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CantidadPacientesSinPlanSaludSinPinResponse")
    @WebResult(name = "CantidadPacientesSinPlanSaludSinPinResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Integer cantidadPacientesSinPlanSaludSinPin()
;

    @WebMethod(operationName = "ObtenerPaciente", action = "http://tempuri.org/IPacientesService/ObtenerPaciente")
    @Action(input = "http://tempuri.org/IPacientesService/ObtenerPaciente", output = "http://tempuri.org/IPacientesService/ObtenerPacienteResponse")
    @RequestWrapper(localName = "ObtenerPaciente", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerPaciente")
    @ResponseWrapper(localName = "ObtenerPacienteResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerPacienteResponse")
    @WebResult(name = "ObtenerPacienteResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules.PacienteModelWrapper obtenerPaciente(

        @WebParam(name = "pacienteId", targetNamespace = "http://tempuri.org/")
        java.lang.String pacienteId,
        @WebParam(name = "codigoPaciente", targetNamespace = "http://tempuri.org/")
        java.lang.Long codigoPaciente,
        @WebParam(name = "historiaClinica", targetNamespace = "http://tempuri.org/")
        java.lang.Long historiaClinica,
        @WebParam(name = "nombre", targetNamespace = "http://tempuri.org/")
        java.lang.String nombre,
        @WebParam(name = "apellido", targetNamespace = "http://tempuri.org/")
        java.lang.String apellido,
        @WebParam(name = "tipoDeDocumento", targetNamespace = "http://tempuri.org/")
        java.lang.String tipoDeDocumento,
        @WebParam(name = "numeroDeDocumento", targetNamespace = "http://tempuri.org/")
        java.lang.String numeroDeDocumento
    );

    @WebMethod(operationName = "ObtenerPacientexTelefono", action = "http://tempuri.org/IPacientesService/ObtenerPacientexTelefono")
    @Action(input = "http://tempuri.org/IPacientesService/ObtenerPacientexTelefono", output = "http://tempuri.org/IPacientesService/ObtenerPacientexTelefonoResponse")
    @RequestWrapper(localName = "ObtenerPacientexTelefono", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerPacientexTelefono")
    @ResponseWrapper(localName = "ObtenerPacientexTelefonoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerPacientexTelefonoResponse")
    @WebResult(name = "ObtenerPacientexTelefonoResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules.PacientesReducidosWrapper obtenerPacientexTelefono(

        @WebParam(name = "sTeleono", targetNamespace = "http://tempuri.org/")
        java.lang.String sTeleono
    );

    @WebMethod(operationName = "ObtenerDactilarRegistrado", action = "http://tempuri.org/IPacientesService/ObtenerDactilarRegistrado")
    @Action(input = "http://tempuri.org/IPacientesService/ObtenerDactilarRegistrado", output = "http://tempuri.org/IPacientesService/ObtenerDactilarRegistradoResponse")
    @RequestWrapper(localName = "ObtenerDactilarRegistrado", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerDactilarRegistrado")
    @ResponseWrapper(localName = "ObtenerDactilarRegistradoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerDactilarRegistradoResponse")
    @WebResult(name = "ObtenerDactilarRegistradoResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules_pacientesservice.DactilarRegistradoModel obtenerDactilarRegistrado(

        @WebParam(name = "tipoDeDocumento", targetNamespace = "http://tempuri.org/")
        java.lang.String tipoDeDocumento,
        @WebParam(name = "numeroDeDocumento", targetNamespace = "http://tempuri.org/")
        java.lang.String numeroDeDocumento
    );

    @WebMethod(operationName = "GetValidacionParaVincularModel", action = "http://tempuri.org/IPacientesService/GetValidacionParaVincularModel")
    @Action(input = "http://tempuri.org/IPacientesService/GetValidacionParaVincularModel", output = "http://tempuri.org/IPacientesService/GetValidacionParaVincularModelResponse")
    @RequestWrapper(localName = "GetValidacionParaVincularModel", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetValidacionParaVincularModel")
    @ResponseWrapper(localName = "GetValidacionParaVincularModelResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetValidacionParaVincularModelResponse")
    @WebResult(name = "GetValidacionParaVincularModelResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules_pacientes.ValidacionParaVincularModelDTO getValidacionParaVincularModel(

        @WebParam(name = "model", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules_pacientes.CreateVinculoModelDTO model
    );

    @WebMethod(operationName = "EnviarMailActivacion", action = "http://tempuri.org/IPacientesService/EnviarMailActivacion")
    @Action(input = "http://tempuri.org/IPacientesService/EnviarMailActivacion", output = "http://tempuri.org/IPacientesService/EnviarMailActivacionResponse")
    @RequestWrapper(localName = "EnviarMailActivacion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EnviarMailActivacion")
    @ResponseWrapper(localName = "EnviarMailActivacionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EnviarMailActivacionResponse")
    @WebResult(name = "EnviarMailActivacionResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules.ResultadoOperacion enviarMailActivacion(

        @WebParam(name = "labCodePaciente", targetNamespace = "http://tempuri.org/")
        java.lang.Long labCodePaciente
    );

    @WebMethod(operationName = "ObtenerPartidos", action = "http://tempuri.org/IPacientesService/ObtenerPartidos")
    @Action(input = "http://tempuri.org/IPacientesService/ObtenerPartidos", output = "http://tempuri.org/IPacientesService/ObtenerPartidosResponse")
    @RequestWrapper(localName = "ObtenerPartidos", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerPartidos")
    @ResponseWrapper(localName = "ObtenerPartidosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerPartidosResponse")
    @WebResult(name = "ObtenerPartidosResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_core.ArrayOfListItemModel obtenerPartidos(

        @WebParam(name = "provincia", targetNamespace = "http://tempuri.org/")
        java.lang.String provincia
    );

    @WebMethod(operationName = "ValidacionOlvidoDeConstraseña", action = "http://tempuri.org/IPacientesService/ValidacionOlvidoDeConstraseña")
    @Action(input = "http://tempuri.org/IPacientesService/ValidacionOlvidoDeConstraseña", output = "http://tempuri.org/IPacientesService/ValidacionOlvidoDeConstraseñaResponse")
    @RequestWrapper(localName = "ValidacionOlvidoDeConstraseña", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidacionOlvidoDeConstraseña")
    @ResponseWrapper(localName = "ValidacionOlvidoDeConstraseñaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidacionOlvidoDeConstraseñaResponse")
    @WebResult(name = "ValidacionOlvidoDeConstraseñaResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules.ResultadoOperacion validacionOlvidoDeConstraseña(

        @WebParam(name = "tipoDeDocumento", targetNamespace = "http://tempuri.org/")
        java.lang.String tipoDeDocumento,
        @WebParam(name = "numeroDeDocumento", targetNamespace = "http://tempuri.org/")
        java.lang.String numeroDeDocumento,
        @WebParam(name = "preguntaSecretaId", targetNamespace = "http://tempuri.org/")
        java.lang.String preguntaSecretaId,
        @WebParam(name = "respuesta", targetNamespace = "http://tempuri.org/")
        java.lang.String respuesta
    );

    @WebMethod(operationName = "EliminarHuellaDigital", action = "http://tempuri.org/IPacientesService/EliminarHuellaDigital")
    @Action(input = "http://tempuri.org/IPacientesService/EliminarHuellaDigital", output = "http://tempuri.org/IPacientesService/EliminarHuellaDigitalResponse")
    @RequestWrapper(localName = "EliminarHuellaDigital", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EliminarHuellaDigital")
    @ResponseWrapper(localName = "EliminarHuellaDigitalResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EliminarHuellaDigitalResponse")
    @WebResult(name = "EliminarHuellaDigitalResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules.ResultadoOperacion eliminarHuellaDigital(

        @WebParam(name = "huella", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules_pacientesservice.HuellaModel huella
    );

    @WebMethod(operationName = "ObtenerPacienteReporte", action = "http://tempuri.org/IPacientesService/ObtenerPacienteReporte")
    @Action(input = "http://tempuri.org/IPacientesService/ObtenerPacienteReporte", output = "http://tempuri.org/IPacientesService/ObtenerPacienteReporteResponse")
    @RequestWrapper(localName = "ObtenerPacienteReporte", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerPacienteReporte")
    @ResponseWrapper(localName = "ObtenerPacienteReporteResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerPacienteReporteResponse")
    @WebResult(name = "ObtenerPacienteReporteResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules.PacienteModelWrapper obtenerPacienteReporte(

        @WebParam(name = "tipoDeDocumento", targetNamespace = "http://tempuri.org/")
        java.lang.String tipoDeDocumento,
        @WebParam(name = "numeroDeDocumento", targetNamespace = "http://tempuri.org/")
        java.lang.String numeroDeDocumento
    );

    @WebMethod(operationName = "TieneCorreoElectronicoConfirmado", action = "http://tempuri.org/IPacientesService/TieneCorreoElectronicoConfirmado")
    @Action(input = "http://tempuri.org/IPacientesService/TieneCorreoElectronicoConfirmado", output = "http://tempuri.org/IPacientesService/TieneCorreoElectronicoConfirmadoResponse")
    @RequestWrapper(localName = "TieneCorreoElectronicoConfirmado", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TieneCorreoElectronicoConfirmado")
    @ResponseWrapper(localName = "TieneCorreoElectronicoConfirmadoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TieneCorreoElectronicoConfirmadoResponse")
    @WebResult(name = "TieneCorreoElectronicoConfirmadoResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Boolean tieneCorreoElectronicoConfirmado(

        @WebParam(name = "pacienteId", targetNamespace = "http://tempuri.org/")
        java.lang.String pacienteId,
        @WebParam(name = "codigoPaciente", targetNamespace = "http://tempuri.org/")
        java.lang.Long codigoPaciente,
        @WebParam(name = "historiaClinica", targetNamespace = "http://tempuri.org/")
        java.lang.Long historiaClinica,
        @WebParam(name = "nombre", targetNamespace = "http://tempuri.org/")
        java.lang.String nombre,
        @WebParam(name = "apellido", targetNamespace = "http://tempuri.org/")
        java.lang.String apellido,
        @WebParam(name = "tipoDeDocumento", targetNamespace = "http://tempuri.org/")
        java.lang.String tipoDeDocumento,
        @WebParam(name = "numeroDeDocumento", targetNamespace = "http://tempuri.org/")
        java.lang.String numeroDeDocumento
    );

    @WebMethod(operationName = "EnviarMailConfirmaCorreoLabCore", action = "http://tempuri.org/IPacientesService/EnviarMailConfirmaCorreoLabCore")
    @Action(input = "http://tempuri.org/IPacientesService/EnviarMailConfirmaCorreoLabCore", output = "http://tempuri.org/IPacientesService/EnviarMailConfirmaCorreoLabCoreResponse")
    @RequestWrapper(localName = "EnviarMailConfirmaCorreoLabCore", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EnviarMailConfirmaCorreoLabCore")
    @ResponseWrapper(localName = "EnviarMailConfirmaCorreoLabCoreResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EnviarMailConfirmaCorreoLabCoreResponse")
    @WebResult(name = "EnviarMailConfirmaCorreoLabCoreResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Boolean enviarMailConfirmaCorreoLabCore(

        @WebParam(name = "_historiaClinica", targetNamespace = "http://tempuri.org/")
        java.lang.String historiaClinica,
        @WebParam(name = "_email", targetNamespace = "http://tempuri.org/")
        java.lang.String email,
        @WebParam(name = "_sede", targetNamespace = "http://tempuri.org/")
        java.lang.String sede
    );

    @WebMethod(operationName = "ObtenerPacientesSinPlanSaludSinPinConEmailValido", action = "http://tempuri.org/IPacientesService/ObtenerPacientesSinPlanSaludSinPinConEmailValido")
    @Action(input = "http://tempuri.org/IPacientesService/ObtenerPacientesSinPlanSaludSinPinConEmailValido", output = "http://tempuri.org/IPacientesService/ObtenerPacientesSinPlanSaludSinPinConEmailValidoResponse")
    @RequestWrapper(localName = "ObtenerPacientesSinPlanSaludSinPinConEmailValido", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerPacientesSinPlanSaludSinPinConEmailValido")
    @ResponseWrapper(localName = "ObtenerPacientesSinPlanSaludSinPinConEmailValidoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerPacientesSinPlanSaludSinPinConEmailValidoResponse")
    @WebResult(name = "ObtenerPacientesSinPlanSaludSinPinConEmailValidoResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules.PacientesReducidosWrapper obtenerPacientesSinPlanSaludSinPinConEmailValido()
;

    @WebMethod(operationName = "ObtenerLinkParaGenerarPin", action = "http://tempuri.org/IPacientesService/ObtenerLinkParaGenerarPin")
    @Action(input = "http://tempuri.org/IPacientesService/ObtenerLinkParaGenerarPin", output = "http://tempuri.org/IPacientesService/ObtenerLinkParaGenerarPinResponse")
    @RequestWrapper(localName = "ObtenerLinkParaGenerarPin", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerLinkParaGenerarPin")
    @ResponseWrapper(localName = "ObtenerLinkParaGenerarPinResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerLinkParaGenerarPinResponse")
    @WebResult(name = "ObtenerLinkParaGenerarPinResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules.PacienteReducidoWrapper obtenerLinkParaGenerarPin(

        @WebParam(name = "pacienteId", targetNamespace = "http://tempuri.org/")
        java.lang.String pacienteId
    );

    @WebMethod(operationName = "ObtenerPacientesConPlanSaludSinPinConEmailValido", action = "http://tempuri.org/IPacientesService/ObtenerPacientesConPlanSaludSinPinConEmailValido")
    @Action(input = "http://tempuri.org/IPacientesService/ObtenerPacientesConPlanSaludSinPinConEmailValido", output = "http://tempuri.org/IPacientesService/ObtenerPacientesConPlanSaludSinPinConEmailValidoResponse")
    @RequestWrapper(localName = "ObtenerPacientesConPlanSaludSinPinConEmailValido", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerPacientesConPlanSaludSinPinConEmailValido")
    @ResponseWrapper(localName = "ObtenerPacientesConPlanSaludSinPinConEmailValidoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerPacientesConPlanSaludSinPinConEmailValidoResponse")
    @WebResult(name = "ObtenerPacientesConPlanSaludSinPinConEmailValidoResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules.PacientesReducidosWrapper obtenerPacientesConPlanSaludSinPinConEmailValido()
;

    @WebMethod(operationName = "EsValidoLinkGeneracionPinMasivo", action = "http://tempuri.org/IPacientesService/EsValidoLinkGeneracionPinMasivo")
    @Action(input = "http://tempuri.org/IPacientesService/EsValidoLinkGeneracionPinMasivo", output = "http://tempuri.org/IPacientesService/EsValidoLinkGeneracionPinMasivoResponse")
    @RequestWrapper(localName = "EsValidoLinkGeneracionPinMasivo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EsValidoLinkGeneracionPinMasivo")
    @ResponseWrapper(localName = "EsValidoLinkGeneracionPinMasivoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EsValidoLinkGeneracionPinMasivoResponse")
    @WebResult(name = "EsValidoLinkGeneracionPinMasivoResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules_pacientesservice.ValidoLinkPinMasivoWrapper esValidoLinkGeneracionPinMasivo(

        @WebParam(name = "linkId", targetNamespace = "http://tempuri.org/")
        java.lang.String linkId,
        @WebParam(name = "pacienteId", targetNamespace = "http://tempuri.org/")
        java.lang.String pacienteId
    );

    @WebMethod(operationName = "ObtenerHuellasDigitales", action = "http://tempuri.org/IPacientesService/ObtenerHuellasDigitales")
    @Action(input = "http://tempuri.org/IPacientesService/ObtenerHuellasDigitales", output = "http://tempuri.org/IPacientesService/ObtenerHuellasDigitalesResponse")
    @RequestWrapper(localName = "ObtenerHuellasDigitales", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerHuellasDigitales")
    @ResponseWrapper(localName = "ObtenerHuellasDigitalesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerHuellasDigitalesResponse")
    @WebResult(name = "ObtenerHuellasDigitalesResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules_pacientesservice.ArrayOfHuellaModel obtenerHuellasDigitales(

        @WebParam(name = "date", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar date
    );

    @WebMethod(operationName = "ObtenerTiposDeVinculo", action = "http://tempuri.org/IPacientesService/ObtenerTiposDeVinculo")
    @Action(input = "http://tempuri.org/IPacientesService/ObtenerTiposDeVinculo", output = "http://tempuri.org/IPacientesService/ObtenerTiposDeVinculoResponse")
    @RequestWrapper(localName = "ObtenerTiposDeVinculo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerTiposDeVinculo")
    @ResponseWrapper(localName = "ObtenerTiposDeVinculoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerTiposDeVinculoResponse")
    @WebResult(name = "ObtenerTiposDeVinculoResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_core.ArrayOfListItemModel obtenerTiposDeVinculo()
;

    @WebMethod(operationName = "ObtenerPaises", action = "http://tempuri.org/IPacientesService/ObtenerPaises")
    @Action(input = "http://tempuri.org/IPacientesService/ObtenerPaises", output = "http://tempuri.org/IPacientesService/ObtenerPaisesResponse")
    @RequestWrapper(localName = "ObtenerPaises", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerPaises")
    @ResponseWrapper(localName = "ObtenerPaisesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerPaisesResponse")
    @WebResult(name = "ObtenerPaisesResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_core.ArrayOfListItemModel obtenerPaises()
;

    @WebMethod(operationName = "BloquearPaciente", action = "http://tempuri.org/IPacientesService/BloquearPaciente")
    @Action(input = "http://tempuri.org/IPacientesService/BloquearPaciente", output = "http://tempuri.org/IPacientesService/BloquearPacienteResponse")
    @RequestWrapper(localName = "BloquearPaciente", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BloquearPaciente")
    @ResponseWrapper(localName = "BloquearPacienteResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BloquearPacienteResponse")
    @WebResult(name = "BloquearPacienteResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Boolean bloquearPaciente(

        @WebParam(name = "pacienteId", targetNamespace = "http://tempuri.org/")
        java.lang.String pacienteId,
        @WebParam(name = "codigoPaciente", targetNamespace = "http://tempuri.org/")
        java.lang.Long codigoPaciente,
        @WebParam(name = "historiaClinica", targetNamespace = "http://tempuri.org/")
        java.lang.Long historiaClinica,
        @WebParam(name = "nombre", targetNamespace = "http://tempuri.org/")
        java.lang.String nombre,
        @WebParam(name = "apellido", targetNamespace = "http://tempuri.org/")
        java.lang.String apellido,
        @WebParam(name = "tipoDeDocumento", targetNamespace = "http://tempuri.org/")
        java.lang.String tipoDeDocumento,
        @WebParam(name = "numeroDeDocumento", targetNamespace = "http://tempuri.org/")
        java.lang.String numeroDeDocumento
    );

    @WebMethod(operationName = "GenerarPinAutomatico", action = "http://tempuri.org/IPacientesService/GenerarPinAutomatico")
    @Action(input = "http://tempuri.org/IPacientesService/GenerarPinAutomatico", output = "http://tempuri.org/IPacientesService/GenerarPinAutomaticoResponse")
    @RequestWrapper(localName = "GenerarPinAutomatico", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerarPinAutomatico")
    @ResponseWrapper(localName = "GenerarPinAutomaticoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerarPinAutomaticoResponse")
    @WebResult(name = "GenerarPinAutomaticoResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules.PinModelWrapper generarPinAutomatico(

        @WebParam(name = "pacienteId", targetNamespace = "http://tempuri.org/")
        java.lang.String pacienteId,
        @WebParam(name = "linkId", targetNamespace = "http://tempuri.org/")
        java.lang.String linkId
    );

    @WebMethod(operationName = "ConfirmarActivacion", action = "http://tempuri.org/IPacientesService/ConfirmarActivacion")
    @Action(input = "http://tempuri.org/IPacientesService/ConfirmarActivacion", output = "http://tempuri.org/IPacientesService/ConfirmarActivacionResponse")
    @RequestWrapper(localName = "ConfirmarActivacion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConfirmarActivacion")
    @ResponseWrapper(localName = "ConfirmarActivacionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConfirmarActivacionResponse")
    @WebResult(name = "ConfirmarActivacionResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules.ResultadoOperacion confirmarActivacion(

        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        java.lang.String token,
        @WebParam(name = "tipoDeDocumento", targetNamespace = "http://tempuri.org/")
        java.lang.String tipoDeDocumento,
        @WebParam(name = "numeroDeDocumento", targetNamespace = "http://tempuri.org/")
        java.lang.String numeroDeDocumento,
        @WebParam(name = "preguntaSecretaId", targetNamespace = "http://tempuri.org/")
        java.lang.String preguntaSecretaId,
        @WebParam(name = "respuesta", targetNamespace = "http://tempuri.org/")
        java.lang.String respuesta,
        @WebParam(name = "clave", targetNamespace = "http://tempuri.org/")
        java.lang.String clave
    );

    @WebMethod(operationName = "CantidadPacientesConPlanSaludSinPin", action = "http://tempuri.org/IPacientesService/CantidadPacientesConPlanSaludSinPin")
    @Action(input = "http://tempuri.org/IPacientesService/CantidadPacientesConPlanSaludSinPin", output = "http://tempuri.org/IPacientesService/CantidadPacientesConPlanSaludSinPinResponse")
    @RequestWrapper(localName = "CantidadPacientesConPlanSaludSinPin", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CantidadPacientesConPlanSaludSinPin")
    @ResponseWrapper(localName = "CantidadPacientesConPlanSaludSinPinResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CantidadPacientesConPlanSaludSinPinResponse")
    @WebResult(name = "CantidadPacientesConPlanSaludSinPinResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Integer cantidadPacientesConPlanSaludSinPin()
;

    @WebMethod(operationName = "EliminarVinculo", action = "http://tempuri.org/IPacientesService/EliminarVinculo")
    @Action(input = "http://tempuri.org/IPacientesService/EliminarVinculo", output = "http://tempuri.org/IPacientesService/EliminarVinculoResponse")
    @RequestWrapper(localName = "EliminarVinculo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EliminarVinculo")
    @ResponseWrapper(localName = "EliminarVinculoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EliminarVinculoResponse")
    @WebResult(name = "EliminarVinculoResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Boolean eliminarVinculo(

        @WebParam(name = "vinculanteId", targetNamespace = "http://tempuri.org/")
        java.lang.String vinculanteId,
        @WebParam(name = "vinculadoId", targetNamespace = "http://tempuri.org/")
        java.lang.String vinculadoId
    );

    @WebMethod(operationName = "TieneLinkValidoParaGenerarPin", action = "http://tempuri.org/IPacientesService/TieneLinkValidoParaGenerarPin")
    @Action(input = "http://tempuri.org/IPacientesService/TieneLinkValidoParaGenerarPin", output = "http://tempuri.org/IPacientesService/TieneLinkValidoParaGenerarPinResponse")
    @RequestWrapper(localName = "TieneLinkValidoParaGenerarPin", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TieneLinkValidoParaGenerarPin")
    @ResponseWrapper(localName = "TieneLinkValidoParaGenerarPinResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TieneLinkValidoParaGenerarPinResponse")
    @WebResult(name = "TieneLinkValidoParaGenerarPinResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Boolean tieneLinkValidoParaGenerarPin(

        @WebParam(name = "pacienteId", targetNamespace = "http://tempuri.org/")
        java.lang.String pacienteId
    );

    @WebMethod(operationName = "CrearVinculo", action = "http://tempuri.org/IPacientesService/CrearVinculo")
    @Action(input = "http://tempuri.org/IPacientesService/CrearVinculo", output = "http://tempuri.org/IPacientesService/CrearVinculoResponse")
    @RequestWrapper(localName = "CrearVinculo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CrearVinculo")
    @ResponseWrapper(localName = "CrearVinculoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CrearVinculoResponse")
    @WebResult(name = "CrearVinculoResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Boolean crearVinculo(

        @WebParam(name = "pacienteId", targetNamespace = "http://tempuri.org/")
        java.lang.String pacienteId,
        @WebParam(name = "vinculo", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.ua_maestrodepacientes_business_modules_pacientes.PacienteVinculoModel vinculo
    );
}
