package org.tempuri;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.4
 * Generated source version: 3.4.4
 *
 */
@WebServiceClient(name = "PacientesService",
                  wsdlLocation = "wsdl/PacientesService-PREPROD.wsdl",
                  targetNamespace = "http://tempuri.org/")
public class PacientesService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "PacientesService");
    public final static QName BasicHttpBindingIPacientesService1 = new QName("http://tempuri.org/", "BasicHttpBinding_IPacientesService1");
    public final static QName BasicHttpBindingIPacientesService = new QName("http://tempuri.org/", "BasicHttpBinding_IPacientesService");
    static {
        URL url = PacientesService.class.getResource("wsdl/PacientesService-PREPROD.wsdl");
        if (url == null) {
            url = PacientesService.class.getClassLoader().getResource("wsdl/PacientesService-PREPROD.wsdl");
        }
        if (url == null) {
            java.util.logging.Logger.getLogger(PacientesService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "wsdl/PacientesService-PREPROD.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PacientesService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PacientesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PacientesService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public PacientesService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PacientesService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PacientesService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IPacientesService
     */
    @WebEndpoint(name = "BasicHttpBinding_IPacientesService1")
    public IPacientesService getBasicHttpBindingIPacientesService1() {
        return super.getPort(BasicHttpBindingIPacientesService1, IPacientesService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IPacientesService
     */
    @WebEndpoint(name = "BasicHttpBinding_IPacientesService1")
    public IPacientesService getBasicHttpBindingIPacientesService1(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIPacientesService1, IPacientesService.class, features);
    }


    /**
     *
     * @return
     *     returns IPacientesService
     */
    @WebEndpoint(name = "BasicHttpBinding_IPacientesService")
    public IPacientesService getBasicHttpBindingIPacientesService() {
        return super.getPort(BasicHttpBindingIPacientesService, IPacientesService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IPacientesService
     */
    @WebEndpoint(name = "BasicHttpBinding_IPacientesService")
    public IPacientesService getBasicHttpBindingIPacientesService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIPacientesService, IPacientesService.class, features);
    }

}
